### ISSUE TITLE
error: 'long unsigned int AccelStepper::_stepInterval' is private

### ISSUE THREAD

**Issue by 5shekel** [sq7bti/iAccelStepper#1] opened 2014-10-30 17:53 UTC
hi, happy to find you library.
as its extends the original library it would help to expand about the install procedure.
as i understood:
- place accelStepper in the library folder of your board
- place iAccelStepper in that same library (overwriting conflict)
  *. import  iAccelStepper.h & AccelStepper.h

what i'm currently getting is 

```
[/opt/energia/hardware/tools/lm4f/bin/arm-none-eabi-g++, -c, -g, -Os, -w, -fno-rtti, -fno-exceptions, -ffunction-sections, -fdata-sections, -mthumb, -mcpu=cortex-m4, -mfloat-abi=hard, -mfpu=fpv4-sp-d16, -fsingle-precision-constant, -DF_CPU=120000000L, -MMD, -DARDUINO=101, -DENERGIA=12, -I/opt/energia/hardware/lm4f/cores/lm4f, -I/opt/energia/hardware/lm4f/variants/launchpad_129, -I/opt/energia/hardware/lm4f/libraries/AccelStepper, /tmp/build8509695019000905233.tmp/sketch_oct30a.cpp, -o, /tmp/build8509695019000905233.tmp/sketch_oct30a.cpp.o]
In file included from sketch_oct30a.ino:1:0:
/opt/energia/hardware/lm4f/libraries/AccelStepper/AccelStepper.h: In member function 'long unsigned int iAccelStepper::stepInterval()':
/opt/energia/hardware/lm4f/libraries/AccelStepper/AccelStepper.h:557:20: error: 'long unsigned int AccelStepper::_stepInterval' is private
In file included from sketch_oct30a.ino:2:0:
/opt/energia/hardware/lm4f/libraries/AccelStepper/iAccelStepper.h:20:41: error: within this context
In file included from sketch_oct30a.ino:1:0:
/opt/energia/hardware/lm4f/libraries/AccelStepper/AccelStepper.h: In member function 'boolean iAccelStepper::difolder of original accelStepperrection()':
/opt/energia/hardware/lm4f/libraries/AccelStepper/AccelStepper.h:596:13: error: 'boolean AccelStepper::_direction' is private
In file included from sketch_oct30a.ino:2:0:
/opt/energia/hardware/lm4f/libraries/AccelStepper/iAccelStepper.h:21:32: error: within this context
```

**Comment by sq7bti** [comment] 2014-10-30 21:14
Expansion of functionality is through inheritance. What you need to do is just place AccelStepper and iAccelStepper library in their folders in the `libraries` folder, like this

```
[bash]$ ls sketchbook/libraries/{,i}AccelStepper
sketchbook/libraries/AccelStepper:
AccelStepper.cpp  AccelStepper.h  AccelStepper.h.save  doc  examples  keywords.txt  LICENSE  Makefile  MANIFEST  project.cfg

sketchbook/libraries/iAccelStepper:
AccelStepper.patch  iAccelStepper.cpp  iAccelStepper.h  keywords.txt  LICENSE  README.md
```

User added libraries are located in the same ${SKETCH_FOLDER} can be checked in the preference file ~/.energia/preferences.txt.

```
sketchbook.path=/home/simon/src/emb/ti/sketchbook
```

Energia would find libraries in the folders:

```
sketchbook.path=/home/simon/src/emb/ti/sketchbook/libraries
```

In the compiler output I can see that you still do not have your AccelStepper.h modified to expose necessary members to a inherited object. You can either apply provided patch or manually edit .h file

I hope that helps.

s.

**Comment by 5shekel** [comment] 2014-10-30 23:31
thank you for the explanation. 
ill test asap

**Comment by 5shekel** [comment] 2014-11-02 16:08
im still having problems.
- both AccelStepper and iAccelStepper in my library folder
- applied patch manually on version 1.45 (1.39 failed as well)
  i testes against the proportional control sketch

``` arduino

#include <iAccelStepper.h>
#include <AccelStepper.h>

// Define a stepper and the pins it will use
AccelStepper stepper(AccelStepper::DRIVER, 3 ,4); // Defaults to AccelStepper::FULL4WIRE (4 pins) on 2, 3, 4, 5

// This defines the analog input pin for reading the control voltage
// Tested with a 10k linear pot between 5v and GND
#define ANALOG_IN A0

void setup()
{  
  stepper.setMaxSpeed(1000);
}

void loop()
{
  // Read new position
  int analog_in = analogRead(ANALOG_IN);
  stepper.moveTo(analog_in);
  stepper.setSpeed(100);
  stepper.runSpeedToPosition();
}
```

```

[/opt/energia/hardware/tools/lm4f/bin/arm-none-eabi-g++, -c, -g, -Os, -w, -fno-rtti, -fno-exceptions, -ffunction-sections, -fdata-sections, -mthumb, -mcpu=cortex-m4, -mfloat-abi=hard, -mfpu=fpv4-sp-d16, -fsingle-precision-constant, -DF_CPU=120000000L, -MMD, -DARDUINO=101, -DENERGIA=12, -I/opt/energia/hardware/lm4f/cores/lm4f, -I/opt/energia/hardware/lm4f/variants/launchpad_129, -I/opt/energia/hardware/lm4f/libraries/iAccelStepper, -I/opt/energia/hardware/lm4f/libraries/AccelStepper, /tmp/build8455673332897300192.tmp/ProportionalControl.cpp, -o, /tmp/build8455673332897300192.tmp/ProportionalControl.cpp.o]
ProportionalControl.pde:15:27: error: no matching function for call to 'AccelStepper::AccelStepper(int, int, int)'
ProportionalControl.pde:15:27: note: candidates are:
In file included from /opt/energia/hardware/lm4f/libraries/iAccelStepper/iAccelStepper.h:5:0,
                 from ProportionalControl.pde:11:
/opt/energia/hardware/lm4f/libraries/AccelStepper/AccelStepper.h:308:5: note: AccelStepper::AccelStepper(void (*)(), void (*)())
/opt/energia/hardware/lm4f/libraries/AccelStepper/AccelStepper.h:308:5: note:   candidate expects 2 arguments, 3 provided
In file included from /opt/energia/hardware/lm4f/libraries/iAccelStepper/iAccelStepper.h:5:0,
                 from ProportionalControl.pde:11:
/opt/energia/hardware/lm4f/libraries/AccelStepper/AccelStepper.h:298:5: note: AccelStepper::AccelStepper()
/opt/energia/hardware/lm4f/libraries/AccelStepper/AccelStepper.h:298:5: note:   candidate expects 0 arguments, 3 provided
/opt/energia/hardware/lm4f/libraries/AccelStepper/AccelStepper.h:251:7: note: AccelStepper::AccelStepper(const AccelStepper&)
/opt/energia/hardware/lm4f/libraries/AccelStepper/AccelStepper.h:251:7: note:   candidate expects 1 argument, 3 provided
```

**Comment by sq7bti** [comment] 2014-11-02 18:36
That looks like new problems.

You need to declare the iAccelStepper to make use of the inherited type, instead of AccelStepper.

I [observed](http://forum.stellarisiti.com/topic/574-lm4f-and-porting-of-accelstepper-lib/?p=4999) that, at least under Energia, it must be declared with a default constructor (empty list of arguments), and instead "configured" with a `.begin()` method in the body of `setup()` function. That's why in the patch you should see that the original constructor is renamed to a begin method:

``` c
-AccelStepper::AccelStepper(uint8_t interface, uint8_t pin1, uint8_t pin2, uint8_t pin3, uint8_t pin4, bool enable)
+void AccelStepper::begin(uint8_t interface, uint8_t pin1, uint8_t pin2, uint8_t pin3, uint8_t pin4, bool enable)
```

Further the arguments of iAccelStepper::begin() is different than AccelStepper::begin()

``` c
  void begin(uint8_t STEP = 2, uint8_t DIR = 3, uint8_t ENABLE = 4);
```

The driver type is [fixed](https://github.com/sq7bti/iAccelStepper/blob/master/iAccelStepper.cpp#L117)  to an equivalent of DRIVER in AccelStepper. Implementation of other drivers (e.g. FULL4WIRE or HALF4WIRE) should be quite simple.

I still see that the headers files (AccelStepper.h and iAccelStepper.h) are located in the Energia system folder, instead of sketches/libraries folder (like `/home/user/folder/where/you/keep/your/sketch_projects/libraries`). Are you sure you modified the correct .h file?

Another remark: this driver does not require to call the `.run()` (or `.runSpeed()` to be precise) as frequent as possible. The execution is taken care by the driver itself by assigning the ISR. What is needed to run is just to call the method `.more()` or `.moveTo()`. Further for a simple test, the constant speed is not necessary. In `loop()` one need just set the target position:

``` arduino
#include <iAccelStepper.h>
#include <AccelStepper.h>

// Define a stepper and the pins it will use
iAccelStepper stepper;

// This defines the analog input pin for reading the control voltage
// Tested with a 10k linear pot between 5v and GND
#define ANALOG_IN A0

void setup()
{  
  stepper.begin(3 ,4);
}

void loop()
{
  // Read new position
  int analog_in = analogRead(ANALOG_IN);
  stepper.moveTo(analog_in);
}
```

**Comment by 5shekel** [comment] 2014-11-02 23:18
ok, some progress.

i successfully compiled your attached example for the STELLARIS board .  
but it seems not to support  the TIVA (TM4C129) board which is the one i used.

thanks so much for your detailed help.

**Comment by sq7bti** [comment] 2014-11-03 08:06
Indeed I am using it for Stellaris launchpad (TM4C123GH6PM). Try adding another chip in the lines #13 and #29

``` c
#if defined(PART_TM4C1233H6PM) || defined(PART_LM4F120H5QR) || defined(PART_TM4C129XNCZAD)
```

s.

**Comment by 5shekel** [comment] 2014-11-03 10:29
ill try, <s>where did you get the part ID, i looked for that one...</s>
oh, i see https://github.com/energia/Energia/blob/master/hardware/lm4f/cores/lm4f/Energia.h

**Comment by sq7bti** [comment] 2015-01-09 12:31
Can you confirm if suggested modification (see comment 61448560) works on your test setup?

**Comment by 5shekel** [comment] 2015-01-09 14:35
sorry a shorted that board :(

On Fri, Jan 9, 2015 at 2:31 PM, sq7bti notifications@github.com wrote:

> Can you confirm if suggested modification (see comment 61448560) works on
> your test setup?
> 
> —
> Reply to this email directly or view it on GitHub
> https://github.com/sq7bti/iAccelStepper/issues/1#issuecomment-69328602.

## 

yair99@gmail
050-6301212
tlv, israel

**Closed as completed** 2019-03-30 12:53 UTC
Labels: question

**Comment by sq7bti** [comment] 2019-03-30 12:54
oop [confirmed](https://github.com/sq7bti/iAccelStepper/issues/1#issuecomment-61428789) solution
